site_name: Plateforme de documentation en Géomatique

theme:
  name: readthedocs

nav:
  - Accueil: index.md
  - Interopérabilité des données en géomatique: Interoperabilite.md
  - Cycle de vie des données: cycle_de_vie_des_donnees.md
  - Admin et Base de données géographique : aide_sql.md
  - Quelques exemples de scripts SQL fréquents en géomatique: abdou_julien_base_de_donnees.md
  - Mise en place de base de données géographique: etude_cas_bdd.md
  - Automatisation de cartes thématiques sur QGIS: Methodologie_carto_diag_auto.md
  - Brique de Géomatqiue et Télédétection: teledetection.md
  - Cartographie avec Rstudio: rstudio_geomatique.md
  - Classification non supervisée d'images: classification_image_kmeans.md
  - Manipulation de données avec commandes GDAL: GDAL_Ubuntu.md
  - Consultation dynamique de données PostgreSQL avec PHP: consultation_presentation_markdown_panel.md
  - Exemple de source de données entreprise : Readme.md
  - Ressources BDTopo: carte_bdtopo.html
  - Carte Pays de Châlons‑en‑Champagne: carte_web.html
extra_css:
  - css/le_style.css


















