site_name: Plateforme de documentation en Géomatique

theme:
  name: readthedocs

nav:
  - Accueil: index.md
  - Interopérabilité des données en géomatique: Interoperabilite.md
  - Admin et Base de données géographique : aide_sql.md
  - Quelques exemples de scripts SQL fréquents en géomatique: abdou_julien_base_de_donnees.md
  - PostGIS 3D: postgis_3d_notes.md
  - PG_Routing 1: pgrouting.md
  - PG_Routing 2: pgrouting1.md
  - Mise en place de base de données géographique: etude_cas_bdd.md
  - Automatisation de cartes thématiques sur QGIS: Methodologie_carto_diag_auto.md
  - Cartographie avec Rstudio: rstudio_geomatique.md
  - Brique de Géomatqiue et Télédétection: teledetection.md
  - Initiation en python 1: python1.md
  - Initiation en python 2: python2.md
  - Initiation en python 3: python3.md
  - Initiation en python 4: python4.md
  - Initiation en python 5: python5.md
  - Initiation en python 6: python6.md
  - Initiation en python 7: python7.md
  - Initiation en python 8: python8.md
  - Initiation en python 9: python9.md
  - Initiation en python 10: python10.md
  - Initiation en python 11: python11.md
  - Initiation en python 12: python12.md
  - Initiation en python 13: python13.md
  - Initiation en python 14: python14.md
  - Initiation en python 15: python15.md
  - Classification non supervisée d'images: classification_image_kmeans.md
  - Classification supervisée d'images: teledetection_cpgeom.md
  - Manipulation de données avec commandes GDAL: GDAL_Ubuntu.md
  - Consultation dynamique de données PostgreSQL avec PHP: consultation_dynamique_script_php.md
  - Exemple de source de données entreprise : Readme.md
  - Carte Pays de Châlons‑en‑Champagne: carte_web.html
extra_css:
  - css/le_style.css


















